apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: twitter-stream
  labels:
    name: twitter-stream
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: twitter-stream
    spec:
      containers:
      - name: twitter-to-pubsub
        image: gcr.io/project_id/pubsub-bq-pipe
        env:
        - name: PROCESSINGSCRIPT
          value: twitter-to-pubsub
        # Change this to your pubsub topic
        - name: PUBSUB_TOPIC
          value: pubsub_topic
        # Change the following four settings to your twitter credentials
        # information.
        - name: CONSUMERKEY
          value: app_key  
        - name: CONSUMERSECRET
          value: app_secret 
        - name: ACCESSTOKEN
          value: oauth_token  
        - name: ACCESSTOKENSEC
          value: oauth_token_secret
        - name: TWSTREAMMODE
          value: sample
